### ISSUE TITLE
Running rpc-wrapper tests in JSDOM environment breaks ability to call into client

### ISSUE THREAD

**Issue by willemolding** [ChainSafe/integrations#28]
To allow the wrapper to use polkadot-js to perform signing it needs to run in a browser (jsdom) environment. Jest tests support this by setting `testEnvironment: "jsdom"`.

Making this change breaks the ability to make calls into the WASM client. Every call fails with:

```shell
expect(received).toBeFalsy()

    Received: [ReferenceError: TextEncoder is not defined]
```

## Steps to replicate

clone branch `willem/switch-rpc-wrapper-tests-to-jsdom` #29 

```shell
cd protocol/substrate/rpc-wrapper/
yarn && yarn test
```

**Comment by dOrgJelli** [comment]
I've seen this error when using an older version of node. We typically use `v16`.

**Comment by dOrgJelli** [comment]
Also we've fixed this error in the Jest browser environment here: https://github.com/polywrap/toolchain/blob/origin/packages/js/react/src/__tests__/env/index.ts
